### ISSUE TITLE
Can we get better documentation of this?

### ISSUE THREAD

**Issue by markosjal** [istopwg/pwg-semantic-model#1]
There is a lot here and I am interested in eSCL Scanner services ffor an embedded portable app ,however not understanding from this information,  how I start making my ScannerCapabilities as there is zero explanation of anything here. 

All examples I see elsewhere on the web are for Platen and ADF but need to see if I can build  ScannerCapabilities for a SINGLE SHEET Sheetfeed scanner , avoiding any preview as it makes no sense to preview then feed the document again for the real scan.

Maybe the "xs:" items relate to "scan:" and "pwg" to "pwg:" in xml? But why the redundancy I can have document types (PDF, JPG, PNG) defined under scan: or pwg: and this seems confusing too. Why two places?

How do I put it all together to understand how to build something compatible with the standard when there are so few available examples anywhere to work from? 

Everything here seems quite cryptic to be honest. I feel like I need to learn a new language and customs to understand it.

I worry that even if I did understand all of this it still would not give me the info I need to do the following

1) Create a ScannerStatus for custom hardware

2) Understand the message flow while a document is scanned, URI sent in "Location: <URI>"

3) Understand How to update ScannerStatus through the course of the process to also include URI (redundant, as URI was already sent in header) , Through "Processing" and "JobCompletedSuccessfully" or is it "Completed" that would be the last message?

In any case how does one get a better overview (preferrably by example) of how these messages are structured through various points in the process? I am 90% there and can Scan into OSX but getting infinite number of the same scan loading in Preview and infinite spinning disk in Image Capture. Of course OSX believes it is a Platen too and it is not.

If this is a standard why can we not get some better documenation? Trade secrets?

**Comment by michaelrsweet** [comment]
@markosjal eSCL is an HP protocol and is NOT documented here or anyplace by the PWG. Your best bet is to contact HP directly.

**Comment by markosjal** [comment]
I thought eSCL is the standard used in Apple AirScan, and used by Canon and others.

PWG seems to define all of the parameters "<pwg:State>Idle</pwg:State> " for instance and has a plethora of related (and convoluted) documentation on their site.

Maybe someone shold better clarify what is the relationship of PWG to some of these standards I suspect that if not PWG then the Mopria Alliance?

Maybe someone should better define then whatever the standard is that is defined by PWG in which case it still lacks a clear flow of communication for scanning. Yes there are docs for printing, much of which does not relate to scanning

**Comment by markosjal** [comment]
I thought eSCL is the standard used in Apple AirScan, and used by Canon and others.

PWG seems to define all of the parameters "<pwg:State>Idle</pwg:State> " for instance and has a plethora of related (and convoluted) documentation on their site.

Maybe someone shouldbetter define then whatever the standard is that is defined by PWG in which case it still lacks a clear flow of communication for scanning. Yes therearedocsforprinting, much of which does not relate to scanning

**Comment by michaelrsweet** [comment]
@markosjal I can't speak to either its usage in AirPrint or in Mopria, as those are not open standards. That eSCL uses some PWG values/semantics is not a surprise - the PWG and its predecessor workgroups in the IETF has defined network printing standards for over 20 years.

**Comment by markosjal** [comment]
Not talking "printing" talking "scanning". There is a difference even the PWG documentation I have read exclude various parameters from scanning which is why I believe scanning needs its own set of documentation If you have to learn all of the printing semantics then throw away half of it , it makes little sense. Printing and scanning are completely different

**Comment by markosjal** [comment]
as I understand it Aprint IS eSCL

**Comment by michaelrsweet** [comment]
AirPrint is NOT eSCL, it just uses it for scanning support. AirPrint is IPP-based.
